[CmdletBinding()]
param([string]$OutputMarkdown='', [string]$OutputJson='')
$ErrorActionPreference='Stop'; $ScriptDir=Split-Path -Parent $MyInvocation.MyCommand.Path; $SkillsRoot=Split-Path -Parent $ScriptDir
if (!$OutputMarkdown) {$OutputMarkdown=Join-Path $SkillsRoot 'tool-index.md'}; if (!$OutputJson) {$OutputJson=Join-Path $SkillsRoot 'tool-index.json'}
$rows=@(
  @('java','runtime','JADX/apktool/bundletool/Ghidra'),@('python3','runtime','Case helpers'),@('node','runtime','Optional MCP bridges'),@('jadx','android','Java/Kotlin decompiler'),@('apktool','android','APK resources and smali'),@('bundletool','android','AAB inspection/splits'),@('dex2jar','android','DEX/JAR conversion'),@('smali','android','DEX assembler'),@('baksmali','android','DEX disassembler'),@('adb','android','Authorized device bridge'),@('zipalign','android','APK alignment'),@('apksigner','android','APK signing'),@('frida','runtime','Dynamic instrumentation'),@('frida-ps','runtime','Frida process listing'),@('objection','runtime','Frida helper'),@('ghidraRun','native','Ghidra GUI'),@('analyzeHeadless','native','Ghidra headless'),@('ida','native','IDA Pro'),@('r2','native','radare2 CLI'),@('rabin2','native','ELF/Mach-O metadata'),@('radiff2','native','Binary diff'),@('rizin','native','Rizin CLI'),@('rz-bin','native','Rizin metadata'),@('lldb','apple','Native debugger'),@('otool','apple','Mach-O load commands'),@('nm','apple','Symbols'),@('codesign','apple','Code signatures'),@('swift-demangle','apple','Swift symbols'),@('dsymutil','apple','Debug symbols'),@('class-dump','apple','Objective-C headers'),@('jtool2','apple','Mach-O inspection'),@('dot','reporting','Graphviz'),@('plantuml','reporting','PlantUML'))
$md=@('# Tool index','',"- Generated: $(Get-Date -Format o)",'- Platform: Windows','- Detection only: no tools are installed.','', '| Tool | Area | Purpose | Available | Path |','|---|---|---|---|---|'); $json=@()
foreach($r in $rows){$c=Get-Command $r[0] -ErrorAction SilentlyContinue; $ok=$null -ne $c; $p=if($ok){$c.Source}else{'—'}; $md += "| $($r[0]) | $($r[1]) | $($r[2]) | $(if($ok){'yes'}else{'no'}) | ``$p`` |"; $json += [pscustomobject]@{name=$r[0];area=$r[1];purpose=$r[2];available=$ok;path=$p}}
$md | Set-Content $OutputMarkdown -Encoding utf8; @{generated_on=(Get-Date -Format o);platform='Windows';tools=$json} | ConvertTo-Json -Depth 5 | Set-Content $OutputJson -Encoding utf8; Write-Host "Wrote $OutputMarkdown and $OutputJson"
